-- Private in-app messaging for Friend Computer Eye.
--
-- Privacy contract:
--   * participant links are revocable capability credentials; only SHA-256
--     digests are stored;
--   * message bodies are encrypted at rest with the room's existing GM-key
--     digest;
--   * the GM RPC intentionally cannot return citizen-to-citizen messages;
--   * player-to-player messaging is disabled unless the GM explicitly enables
--     it for the room.

create table public.fc_message_settings (
  room text primary key references public.fc_sessions(room) on delete cascade,
  allow_player_to_player boolean not null default false,
  retention_hours smallint not null default 168
    check (retention_hours between 1 and 720),
  updated_at timestamptz not null default now()
);

create table public.fc_message_participants (
  room text not null,
  seat smallint not null,
  token_hash bytea not null unique check (octet_length(token_hash) = 32),
  issued_at timestamptz not null default now(),
  expires_at timestamptz not null default (now() + interval '30 days'),
  revoked_at timestamptz,
  last_seen_at timestamptz,
  primary key (room, seat),
  foreign key (room, seat)
    references public.fc_citizens(room, seat) on delete cascade,
  check (expires_at > issued_at)
);

create table public.fc_direct_messages (
  id bigint generated by default as identity primary key,
  room text not null references public.fc_sessions(room) on delete cascade,
  sender_kind text not null check (sender_kind in ('gm', 'citizen')),
  sender_seat smallint,
  recipient_kind text not null check (recipient_kind in ('gm', 'citizen')),
  recipient_seat smallint,
  body_cipher bytea not null,
  created_at timestamptz not null default now(),
  read_at timestamptz,
  foreign key (room, sender_seat)
    references public.fc_citizens(room, seat) on delete cascade,
  foreign key (room, recipient_seat)
    references public.fc_citizens(room, seat) on delete cascade,
  check (
    (sender_kind = 'gm' and sender_seat is null and recipient_kind = 'citizen' and recipient_seat is not null)
    or
    (sender_kind = 'citizen' and sender_seat is not null and recipient_kind = 'gm' and recipient_seat is null)
    or
    (sender_kind = 'citizen' and sender_seat is not null and recipient_kind = 'citizen'
      and recipient_seat is not null and recipient_seat <> sender_seat)
  )
);

create index fc_message_participants_active_idx
  on public.fc_message_participants (room, seat, expires_at)
  where revoked_at is null;

create index fc_direct_messages_room_created_idx
  on public.fc_direct_messages (room, created_at desc, id desc);

create index fc_direct_messages_recipient_idx
  on public.fc_direct_messages (room, recipient_kind, recipient_seat, created_at desc, id desc);

create index fc_direct_messages_sender_idx
  on public.fc_direct_messages (room, sender_kind, sender_seat, created_at desc, id desc);

create index fc_direct_messages_unread_idx
  on public.fc_direct_messages (room, recipient_kind, recipient_seat, created_at desc)
  where read_at is null;

alter table public.fc_message_settings enable row level security;
alter table public.fc_message_participants enable row level security;
alter table public.fc_direct_messages enable row level security;

revoke all on table public.fc_message_settings from public, anon, authenticated;
revoke all on table public.fc_message_participants from public, anon, authenticated;
revoke all on table public.fc_direct_messages from public, anon, authenticated;
revoke all on sequence public.fc_direct_messages_id_seq from public, anon, authenticated;

create or replace function public.fc_message_prune(p_room text)
returns void
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  keep_hours integer;
begin
  select coalesce(s.retention_hours, 168)
    into keep_hours
  from public.fc_message_settings s
  where s.room = p_room;

  delete from public.fc_direct_messages m
  where m.room = p_room
    and m.created_at < now() - make_interval(hours => coalesce(keep_hours, 168));
end;
$function$;

create or replace function public.fc_message_token_identity(p_token text)
returns table(room text, seat smallint, gm_key_hash bytea)
language sql
stable
security definer
set search_path = public, extensions
as $function$
  select p.room, p.seat, s.gm_key_hash
  from public.fc_message_participants p
  join public.fc_sessions s on s.room = p.room
  where p.token_hash = extensions.digest(convert_to(p_token, 'UTF8'), 'sha256')
    and p.revoked_at is null
    and p.expires_at > now()
    and p_token is not null
    and char_length(p_token) between 20 and 200
  limit 1;
$function$;

revoke all on function public.fc_message_prune(text) from public, anon, authenticated;
revoke all on function public.fc_message_token_identity(text) from public, anon, authenticated;

create or replace function public.fc_message_gm_settings(p_room text, p_gm_key text)
returns table(
  allow_player_to_player boolean,
  retention_hours smallint,
  gm_can_read_player_to_player boolean
)
language plpgsql
security definer
set search_path = public, extensions
as $function$
begin
  if not public.fc_ensure_session(p_room, p_gm_key) then return; end if;

  insert into public.fc_message_settings(room)
  values (p_room)
  on conflict (room) do nothing;

  return query
  select s.allow_player_to_player, s.retention_hours, false
  from public.fc_message_settings s
  where s.room = p_room;
end;
$function$;

create or replace function public.fc_message_gm_update_settings(
  p_room text,
  p_gm_key text,
  p_allow_player_to_player boolean,
  p_retention_hours integer
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $function$
begin
  if not public.fc_ensure_session(p_room, p_gm_key) then return false; end if;
  if p_retention_hours is null or p_retention_hours < 1 or p_retention_hours > 720 then return false; end if;

  insert into public.fc_message_settings(room, allow_player_to_player, retention_hours, updated_at)
  values (p_room, coalesce(p_allow_player_to_player, false), p_retention_hours, now())
  on conflict (room) do update
    set allow_player_to_player = excluded.allow_player_to_player,
        retention_hours = excluded.retention_hours,
        updated_at = now();

  perform public.fc_message_prune(p_room);
  return true;
end;
$function$;

create or replace function public.fc_message_gm_invites(p_room text, p_gm_key text)
returns table(
  seat smallint,
  citizen_id text,
  display_name text,
  invite_active boolean,
  expires_at timestamptz,
  last_seen_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $function$
begin
  if not public.fc_ensure_session(p_room, p_gm_key) then return; end if;

  return query
  select c.seat,
         c.citizen_id,
         c.display_name,
         (p.revoked_at is null and p.expires_at > now()),
         p.expires_at,
         p.last_seen_at
  from public.fc_citizens c
  left join public.fc_message_participants p
    on p.room = c.room and p.seat = c.seat
  where c.room = p_room
  order by c.seat;
end;
$function$;

create or replace function public.fc_message_gm_issue_token(
  p_room text,
  p_gm_key text,
  p_seat integer,
  p_token text
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $function$
begin
  if not public.fc_ensure_session(p_room, p_gm_key) then return false; end if;
  if p_token is null or char_length(p_token) < 20 or char_length(p_token) > 200 then return false; end if;
  if not exists (
    select 1 from public.fc_citizens c where c.room = p_room and c.seat = p_seat
  ) then return false; end if;

  insert into public.fc_message_participants(
    room, seat, token_hash, issued_at, expires_at, revoked_at, last_seen_at
  )
  values (
    p_room,
    p_seat::smallint,
    extensions.digest(convert_to(p_token, 'UTF8'), 'sha256'),
    now(),
    now() + interval '30 days',
    null,
    null
  )
  on conflict (room, seat) do update
    set token_hash = excluded.token_hash,
        issued_at = excluded.issued_at,
        expires_at = excluded.expires_at,
        revoked_at = null,
        last_seen_at = null;

  return true;
end;
$function$;

create or replace function public.fc_message_gm_revoke_token(
  p_room text,
  p_gm_key text,
  p_seat integer
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $function$
begin
  if not public.fc_ensure_session(p_room, p_gm_key) then return false; end if;

  update public.fc_message_participants p
  set revoked_at = now()
  where p.room = p_room and p.seat = p_seat;

  return found;
end;
$function$;

create or replace function public.fc_message_gm_list(
  p_room text,
  p_gm_key text,
  p_limit integer default 100
)
returns table(
  id bigint,
  sender_kind text,
  sender_seat smallint,
  sender_name text,
  recipient_kind text,
  recipient_seat smallint,
  recipient_name text,
  body text,
  created_at timestamptz,
  read_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $function$
begin
  if not public.fc_ensure_session(p_room, p_gm_key) then return; end if;
  perform public.fc_message_prune(p_room);

  return query
  select m.id,
         m.sender_kind,
         m.sender_seat,
         case when m.sender_kind = 'gm' then 'GM' else sc.display_name end,
         m.recipient_kind,
         m.recipient_seat,
         case when m.recipient_kind = 'gm' then 'GM' else rc.display_name end,
         extensions.pgp_sym_decrypt(m.body_cipher, encode(s.gm_key_hash, 'hex')),
         m.created_at,
         m.read_at
  from public.fc_direct_messages m
  join public.fc_sessions s on s.room = m.room
  left join public.fc_citizens sc on sc.room = m.room and sc.seat = m.sender_seat
  left join public.fc_citizens rc on rc.room = m.room and rc.seat = m.recipient_seat
  where m.room = p_room
    and (m.sender_kind = 'gm' or m.recipient_kind = 'gm')
  order by m.created_at desc, m.id desc
  limit greatest(1, least(coalesce(p_limit, 100), 200));
end;
$function$;

create or replace function public.fc_message_gm_send(
  p_room text,
  p_gm_key text,
  p_recipient_seat integer,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  room_hash bytea;
  message_id bigint;
begin
  if not public.fc_ensure_session(p_room, p_gm_key) then return null; end if;
  if p_body is null or char_length(btrim(p_body)) < 1 or char_length(p_body) > 2000 then return null; end if;
  if not exists (
    select 1 from public.fc_citizens c where c.room = p_room and c.seat = p_recipient_seat
  ) then return null; end if;

  select s.gm_key_hash into room_hash from public.fc_sessions s where s.room = p_room;
  perform public.fc_message_prune(p_room);

  if (
    select count(*) >= 20
    from public.fc_direct_messages m
    where m.room = p_room
      and m.sender_kind = 'gm'
      and m.created_at >= now() - interval '1 minute'
  ) then return null; end if;

  insert into public.fc_direct_messages(
    room, sender_kind, sender_seat, recipient_kind, recipient_seat, body_cipher
  )
  values (
    p_room,
    'gm',
    null,
    'citizen',
    p_recipient_seat::smallint,
    extensions.pgp_sym_encrypt(btrim(p_body), encode(room_hash, 'hex'))
  )
  returning public.fc_direct_messages.id into message_id;

  return message_id;
end;
$function$;

create or replace function public.fc_message_gm_mark_read(
  p_room text,
  p_gm_key text,
  p_sender_seat integer default null
)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  changed integer;
begin
  if not public.fc_ensure_session(p_room, p_gm_key) then return 0; end if;

  update public.fc_direct_messages m
  set read_at = now()
  where m.room = p_room
    and m.sender_kind = 'citizen'
    and m.recipient_kind = 'gm'
    and m.read_at is null
    and (p_sender_seat is null or m.sender_seat = p_sender_seat);

  get diagnostics changed = row_count;
  return changed;
end;
$function$;

create or replace function public.fc_message_gm_delete_all(p_room text, p_gm_key text)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  changed integer;
begin
  if not public.fc_ensure_session(p_room, p_gm_key) then return 0; end if;
  delete from public.fc_direct_messages m where m.room = p_room;
  get diagnostics changed = row_count;
  return changed;
end;
$function$;

create or replace function public.fc_message_player_identity(p_token text)
returns table(
  room text,
  seat smallint,
  citizen_id text,
  display_name text,
  allow_player_to_player boolean,
  retention_hours smallint,
  gm_can_read_player_to_player boolean,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  token_room text;
  token_seat smallint;
begin
  select i.room, i.seat into token_room, token_seat
  from public.fc_message_token_identity(p_token) i;
  if token_room is null then return; end if;

  update public.fc_message_participants p
  set last_seen_at = now()
  where p.room = token_room
    and p.seat = token_seat
    and (p.last_seen_at is null or p.last_seen_at < now() - interval '1 minute');

  return query
  select c.room,
         c.seat,
         c.citizen_id,
         c.display_name,
         coalesce(s.allow_player_to_player, false),
         coalesce(s.retention_hours, 168::smallint),
         false,
         p.expires_at
  from public.fc_citizens c
  join public.fc_message_participants p on p.room = c.room and p.seat = c.seat
  left join public.fc_message_settings s on s.room = c.room
  where c.room = token_room and c.seat = token_seat;
end;
$function$;

create or replace function public.fc_message_player_directory(p_token text)
returns table(seat smallint, citizen_id text, display_name text)
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  token_room text;
  token_seat smallint;
  p2p_enabled boolean;
begin
  select i.room, i.seat into token_room, token_seat
  from public.fc_message_token_identity(p_token) i;
  if token_room is null then return; end if;

  select coalesce(s.allow_player_to_player, false) into p2p_enabled
  from public.fc_message_settings s where s.room = token_room;
  if not coalesce(p2p_enabled, false) then return; end if;

  return query
  select c.seat, c.citizen_id, c.display_name
  from public.fc_citizens c
  where c.room = token_room and c.seat <> token_seat
  order by c.seat;
end;
$function$;

create or replace function public.fc_message_player_list(
  p_token text,
  p_limit integer default 100
)
returns table(
  id bigint,
  sender_kind text,
  sender_seat smallint,
  sender_name text,
  recipient_kind text,
  recipient_seat smallint,
  recipient_name text,
  body text,
  created_at timestamptz,
  read_at timestamptz
)
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  token_room text;
  token_seat smallint;
  room_hash bytea;
begin
  select i.room, i.seat, i.gm_key_hash into token_room, token_seat, room_hash
  from public.fc_message_token_identity(p_token) i;
  if token_room is null then return; end if;
  perform public.fc_message_prune(token_room);

  return query
  select m.id,
         m.sender_kind,
         m.sender_seat,
         case when m.sender_kind = 'gm' then 'GM' else sc.display_name end,
         m.recipient_kind,
         m.recipient_seat,
         case when m.recipient_kind = 'gm' then 'GM' else rc.display_name end,
         extensions.pgp_sym_decrypt(m.body_cipher, encode(room_hash, 'hex')),
         m.created_at,
         m.read_at
  from public.fc_direct_messages m
  left join public.fc_citizens sc on sc.room = m.room and sc.seat = m.sender_seat
  left join public.fc_citizens rc on rc.room = m.room and rc.seat = m.recipient_seat
  where m.room = token_room
    and ((m.sender_kind = 'citizen' and m.sender_seat = token_seat)
      or (m.recipient_kind = 'citizen' and m.recipient_seat = token_seat))
  order by m.created_at desc, m.id desc
  limit greatest(1, least(coalesce(p_limit, 100), 200));
end;
$function$;

create or replace function public.fc_message_player_send(
  p_token text,
  p_recipient_kind text,
  p_recipient_seat integer,
  p_body text
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  token_room text;
  token_seat smallint;
  room_hash bytea;
  p2p_enabled boolean;
  message_id bigint;
begin
  select i.room, i.seat, i.gm_key_hash into token_room, token_seat, room_hash
  from public.fc_message_token_identity(p_token) i;
  if token_room is null then return null; end if;
  if p_body is null or char_length(btrim(p_body)) < 1 or char_length(p_body) > 2000 then return null; end if;

  if p_recipient_kind = 'gm' then
    p_recipient_seat := null;
  elsif p_recipient_kind = 'citizen' then
    select coalesce(s.allow_player_to_player, false) into p2p_enabled
    from public.fc_message_settings s where s.room = token_room;
    if not coalesce(p2p_enabled, false) or p_recipient_seat is null or p_recipient_seat = token_seat then
      return null;
    end if;
    if not exists (
      select 1 from public.fc_citizens c where c.room = token_room and c.seat = p_recipient_seat
    ) then return null; end if;
  else
    return null;
  end if;

  perform public.fc_message_prune(token_room);
  if (
    select count(*) >= 20
    from public.fc_direct_messages m
    where m.room = token_room
      and m.sender_kind = 'citizen'
      and m.sender_seat = token_seat
      and m.created_at >= now() - interval '1 minute'
  ) then return null; end if;

  insert into public.fc_direct_messages(
    room, sender_kind, sender_seat, recipient_kind, recipient_seat, body_cipher
  )
  values (
    token_room,
    'citizen',
    token_seat,
    p_recipient_kind,
    p_recipient_seat::smallint,
    extensions.pgp_sym_encrypt(btrim(p_body), encode(room_hash, 'hex'))
  )
  returning public.fc_direct_messages.id into message_id;

  return message_id;
end;
$function$;

create or replace function public.fc_message_player_mark_read(
  p_token text,
  p_sender_kind text,
  p_sender_seat integer default null
)
returns integer
language plpgsql
security definer
set search_path = public, extensions
as $function$
declare
  token_room text;
  token_seat smallint;
  changed integer;
begin
  select i.room, i.seat into token_room, token_seat
  from public.fc_message_token_identity(p_token) i;
  if token_room is null then return 0; end if;

  update public.fc_direct_messages m
  set read_at = now()
  where m.room = token_room
    and m.recipient_kind = 'citizen'
    and m.recipient_seat = token_seat
    and m.read_at is null
    and (
      (p_sender_kind = 'gm' and m.sender_kind = 'gm')
      or (p_sender_kind = 'citizen' and m.sender_kind = 'citizen' and m.sender_seat = p_sender_seat)
    );

  get diagnostics changed = row_count;
  return changed;
end;
$function$;

revoke all on function public.fc_message_gm_settings(text, text) from public, anon, authenticated;
revoke all on function public.fc_message_gm_update_settings(text, text, boolean, integer) from public, anon, authenticated;
revoke all on function public.fc_message_gm_invites(text, text) from public, anon, authenticated;
revoke all on function public.fc_message_gm_issue_token(text, text, integer, text) from public, anon, authenticated;
revoke all on function public.fc_message_gm_revoke_token(text, text, integer) from public, anon, authenticated;
revoke all on function public.fc_message_gm_list(text, text, integer) from public, anon, authenticated;
revoke all on function public.fc_message_gm_send(text, text, integer, text) from public, anon, authenticated;
revoke all on function public.fc_message_gm_mark_read(text, text, integer) from public, anon, authenticated;
revoke all on function public.fc_message_gm_delete_all(text, text) from public, anon, authenticated;
revoke all on function public.fc_message_player_identity(text) from public, anon, authenticated;
revoke all on function public.fc_message_player_directory(text) from public, anon, authenticated;
revoke all on function public.fc_message_player_list(text, integer) from public, anon, authenticated;
revoke all on function public.fc_message_player_send(text, text, integer, text) from public, anon, authenticated;
revoke all on function public.fc_message_player_mark_read(text, text, integer) from public, anon, authenticated;

grant execute on function public.fc_message_gm_settings(text, text) to anon;
grant execute on function public.fc_message_gm_update_settings(text, text, boolean, integer) to anon;
grant execute on function public.fc_message_gm_invites(text, text) to anon;
grant execute on function public.fc_message_gm_issue_token(text, text, integer, text) to anon;
grant execute on function public.fc_message_gm_revoke_token(text, text, integer) to anon;
grant execute on function public.fc_message_gm_list(text, text, integer) to anon;
grant execute on function public.fc_message_gm_send(text, text, integer, text) to anon;
grant execute on function public.fc_message_gm_mark_read(text, text, integer) to anon;
grant execute on function public.fc_message_gm_delete_all(text, text) to anon;
grant execute on function public.fc_message_player_identity(text) to anon;
grant execute on function public.fc_message_player_directory(text) to anon;
grant execute on function public.fc_message_player_list(text, integer) to anon;
grant execute on function public.fc_message_player_send(text, text, integer, text) to anon;
grant execute on function public.fc_message_player_mark_read(text, text, integer) to anon;

notify pgrst, 'reload schema';
